name: build image

on:
  push:
    branches:
      - master
  release:
    types: [published, created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin
      - name: build the image
        env:
          TAG: ${{ref}}
        run: |
          docker buildx build --push \
            --tag apipa169/assistant-relay-docker:latest \
            --tag apipa169/assistant-relay-docker:${env:TAG} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .
