name: build image

on:
  release:
    types: [published, created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: Show version
        run: echo ${{ steps.get_version.outputs.VERSION }} 
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          buildx-version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u "${{ secrets.DOCKER_HUB_USER }}" --password-stdin
      - name: build the image
        run: |
          docker buildx build --push \
            --tag apipa169/assistant-relay-docker:latest \
            --tag apipa169/assistant-relay-docker:${{ steps.get_version.outputs.VERSION }} \
            --env BUILD_VERSION=${{ steps.get_version.outputs.VERSION }} \
            --platform linux/amd64,linux/arm/v7,linux/arm64 .